CREATE TABLE TESTDATA (ROWID INTEGER NOT NULL,
        TITLE VARCHAR(32),
        NOTES VARCHAR(64) CHARACTER SET ISO8859_1,
        BLOBDATA BLOB SUB_TYPE TEXT SEGMENT SIZE 80 CHARACTER SET WIN1252,
        INCLEAR VARCHAR(16) CHARACTER SET NONE,
PRIMARY KEY (ROWID));

