[requires]
packages=fcl-res
libc=y

[compiler]
options= -MObjFPC -Scghi -Cg -Cr -O1 -g -gl -gh -l -vewnhibq -dUseCThreads

unittargetdir=testunits/$(CPU_TARGET)-$(OS_TARGET)
includedir=../include
unitdir=testApp  . ../runtime/nongui ../iblocaldb/nongui

[target]
programs=testsuite 



